# Generated by Django 3.2.8 on 2022-01-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='fgh', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
